version: '3.9'
services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
    command: --api.insecure=true --providers.docker

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - web
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=postgresql
    restart: unless-stopped
    networks:
      - web
    ports:
      - "5432:5432"

networks:
  web:
    external: true
