# Generated by Django 5.0.1 on 2024-01-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.DeleteModel(
            name='ProductCartAssociation',
        ),
    ]
